//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouInteractV1.DSDWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://dsd.av.it.pt/dsdws", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dsd.av.it.pt/dsdws", ConfigurationName="DSDWS.WSSoap")]
    public interface WSSoap {
        
        // CODEGEN: Generating message contract since element name getSemestresResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getSemestres", ReplyAction="*")]
        YouInteractV1.DSDWS.getSemestresResponse getSemestres(YouInteractV1.DSDWS.getSemestresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getSemestres", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getSemestresResponse> getSemestresAsync(YouInteractV1.DSDWS.getSemestresRequest request);
        
        // CODEGEN: Generating message contract since element name getTiposSalaResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getTiposSala", ReplyAction="*")]
        YouInteractV1.DSDWS.getTiposSalaResponse getTiposSala(YouInteractV1.DSDWS.getTiposSalaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getTiposSala", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getTiposSalaResponse> getTiposSalaAsync(YouInteractV1.DSDWS.getTiposSalaRequest request);
        
        // CODEGEN: Generating message contract since element name getSalasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getSalas", ReplyAction="*")]
        YouInteractV1.DSDWS.getSalasResponse getSalas(YouInteractV1.DSDWS.getSalasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getSalas", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getSalasResponse> getSalasAsync(YouInteractV1.DSDWS.getSalasRequest request);
        
        // CODEGEN: Generating message contract since element name getCursosResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getCursos", ReplyAction="*")]
        YouInteractV1.DSDWS.getCursosResponse getCursos(YouInteractV1.DSDWS.getCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getCursos", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getCursosResponse> getCursosAsync(YouInteractV1.DSDWS.getCursosRequest request);
        
        // CODEGEN: Generating message contract since element name getDepartamentosResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDepartamentos", ReplyAction="*")]
        YouInteractV1.DSDWS.getDepartamentosResponse getDepartamentos(YouInteractV1.DSDWS.getDepartamentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDepartamentos", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDepartamentosResponse> getDepartamentosAsync(YouInteractV1.DSDWS.getDepartamentosRequest request);
        
        // CODEGEN: Generating message contract since element name getAreasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getAreas", ReplyAction="*")]
        YouInteractV1.DSDWS.getAreasResponse getAreas(YouInteractV1.DSDWS.getAreasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getAreas", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getAreasResponse> getAreasAsync(YouInteractV1.DSDWS.getAreasRequest request);
        
        // CODEGEN: Generating message contract since element name getSubAreasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getSubAreas", ReplyAction="*")]
        YouInteractV1.DSDWS.getSubAreasResponse getSubAreas(YouInteractV1.DSDWS.getSubAreasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getSubAreas", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getSubAreasResponse> getSubAreasAsync(YouInteractV1.DSDWS.getSubAreasRequest request);
        
        // CODEGEN: Generating message contract since element name getDocentesResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDocentes", ReplyAction="*")]
        YouInteractV1.DSDWS.getDocentesResponse getDocentes(YouInteractV1.DSDWS.getDocentesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDocentes", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDocentesResponse> getDocentesAsync(YouInteractV1.DSDWS.getDocentesRequest request);
        
        // CODEGEN: Generating message contract since element name getDocentesAnoResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDocentesAno", ReplyAction="*")]
        YouInteractV1.DSDWS.getDocentesAnoResponse getDocentesAno(YouInteractV1.DSDWS.getDocentesAnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDocentesAno", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDocentesAnoResponse> getDocentesAnoAsync(YouInteractV1.DSDWS.getDocentesAnoRequest request);
        
        // CODEGEN: Generating message contract since element name getDisciplinasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDisciplinas", ReplyAction="*")]
        YouInteractV1.DSDWS.getDisciplinasResponse getDisciplinas(YouInteractV1.DSDWS.getDisciplinasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDisciplinas", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDisciplinasResponse> getDisciplinasAsync(YouInteractV1.DSDWS.getDisciplinasRequest request);
        
        // CODEGEN: Generating message contract since element name getDisciplinasAnoResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDisciplinasAno", ReplyAction="*")]
        YouInteractV1.DSDWS.getDisciplinasAnoResponse getDisciplinasAno(YouInteractV1.DSDWS.getDisciplinasAnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDisciplinasAno", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDisciplinasAnoResponse> getDisciplinasAnoAsync(YouInteractV1.DSDWS.getDisciplinasAnoRequest request);
        
        // CODEGEN: Generating message contract since element name getTurmasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getTurmas", ReplyAction="*")]
        YouInteractV1.DSDWS.getTurmasResponse getTurmas(YouInteractV1.DSDWS.getTurmasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getTurmas", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getTurmasResponse> getTurmasAsync(YouInteractV1.DSDWS.getTurmasRequest request);
        
        // CODEGEN: Generating message contract since element name getAulasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getAulas", ReplyAction="*")]
        YouInteractV1.DSDWS.getAulasResponse getAulas(YouInteractV1.DSDWS.getAulasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getAulas", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getAulasResponse> getAulasAsync(YouInteractV1.DSDWS.getAulasRequest request);
        
        // CODEGEN: Generating message contract since element name getTurmasHoraResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getTurmasHora", ReplyAction="*")]
        YouInteractV1.DSDWS.getTurmasHoraResponse getTurmasHora(YouInteractV1.DSDWS.getTurmasHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getTurmasHora", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getTurmasHoraResponse> getTurmasHoraAsync(YouInteractV1.DSDWS.getTurmasHoraRequest request);
        
        // CODEGEN: Generating message contract since element name getWishListResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getWishList", ReplyAction="*")]
        YouInteractV1.DSDWS.getWishListResponse getWishList(YouInteractV1.DSDWS.getWishListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getWishList", ReplyAction="*")]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getWishListResponse> getWishListAsync(YouInteractV1.DSDWS.getWishListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSemestresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSemestres", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getSemestresRequestBody Body;
        
        public getSemestresRequest() {
        }
        
        public getSemestresRequest(YouInteractV1.DSDWS.getSemestresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSemestresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getSemestresRequestBody() {
        }
        
        public getSemestresRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSemestresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSemestresResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getSemestresResponseBody Body;
        
        public getSemestresResponse() {
        }
        
        public getSemestresResponse(YouInteractV1.DSDWS.getSemestresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSemestresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.Semestre[] getSemestresResult;
        
        public getSemestresResponseBody() {
        }
        
        public getSemestresResponseBody(You_TimeTables.DSDWS.Semestre[] getSemestresResult) {
            this.getSemestresResult = getSemestresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTiposSalaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTiposSala", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getTiposSalaRequestBody Body;
        
        public getTiposSalaRequest() {
        }
        
        public getTiposSalaRequest(YouInteractV1.DSDWS.getTiposSalaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTiposSalaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getTiposSalaRequestBody() {
        }
        
        public getTiposSalaRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTiposSalaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTiposSalaResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getTiposSalaResponseBody Body;
        
        public getTiposSalaResponse() {
        }
        
        public getTiposSalaResponse(YouInteractV1.DSDWS.getTiposSalaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTiposSalaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.TipoSala[] getTiposSalaResult;
        
        public getTiposSalaResponseBody() {
        }
        
        public getTiposSalaResponseBody(You_TimeTables.DSDWS.TipoSala[] getTiposSalaResult) {
            this.getTiposSalaResult = getTiposSalaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSalasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSalas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getSalasRequestBody Body;
        
        public getSalasRequest() {
        }
        
        public getSalasRequest(YouInteractV1.DSDWS.getSalasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSalasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Rev;
        
        public getSalasRequestBody() {
        }
        
        public getSalasRequestBody(int IDDepartamento, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSalasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSalasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getSalasResponseBody Body;
        
        public getSalasResponse() {
        }
        
        public getSalasResponse(YouInteractV1.DSDWS.getSalasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSalasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.Sala[] getSalasResult;
        
        public getSalasResponseBody() {
        }
        
        public getSalasResponseBody(You_TimeTables.DSDWS.Sala[] getSalasResult) {
            this.getSalasResult = getSalasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCursosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCursos", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getCursosRequestBody Body;
        
        public getCursosRequest() {
        }
        
        public getCursosRequest(YouInteractV1.DSDWS.getCursosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getCursosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Rev;
        
        public getCursosRequestBody() {
        }
        
        public getCursosRequestBody(int IDDepartamento, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCursosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCursosResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getCursosResponseBody Body;
        
        public getCursosResponse() {
        }
        
        public getCursosResponse(YouInteractV1.DSDWS.getCursosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getCursosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.Curso[] getCursosResult;
        
        public getCursosResponseBody() {
        }
        
        public getCursosResponseBody(You_TimeTables.DSDWS.Curso[] getCursosResult) {
            this.getCursosResult = getCursosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDepartamentosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDepartamentos", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDepartamentosRequestBody Body;
        
        public getDepartamentosRequest() {
        }
        
        public getDepartamentosRequest(YouInteractV1.DSDWS.getDepartamentosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDepartamentosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getDepartamentosRequestBody() {
        }
        
        public getDepartamentosRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDepartamentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDepartamentosResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDepartamentosResponseBody Body;
        
        public getDepartamentosResponse() {
        }
        
        public getDepartamentosResponse(YouInteractV1.DSDWS.getDepartamentosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDepartamentosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.Departamento[] getDepartamentosResult;
        
        public getDepartamentosResponseBody() {
        }
        
        public getDepartamentosResponseBody(You_TimeTables.DSDWS.Departamento[] getDepartamentosResult) {
            this.getDepartamentosResult = getDepartamentosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAreasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAreas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getAreasRequestBody Body;
        
        public getAreasRequest() {
        }
        
        public getAreasRequest(YouInteractV1.DSDWS.getAreasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getAreasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getAreasRequestBody() {
        }
        
        public getAreasRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAreasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAreasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getAreasResponseBody Body;
        
        public getAreasResponse() {
        }
        
        public getAreasResponse(YouInteractV1.DSDWS.getAreasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getAreasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.Area[] getAreasResult;
        
        public getAreasResponseBody() {
        }
        
        public getAreasResponseBody(You_TimeTables.DSDWS.Area[] getAreasResult) {
            this.getAreasResult = getAreasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubAreasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSubAreas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getSubAreasRequestBody Body;
        
        public getSubAreasRequest() {
        }
        
        public getSubAreasRequest(YouInteractV1.DSDWS.getSubAreasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSubAreasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getSubAreasRequestBody() {
        }
        
        public getSubAreasRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubAreasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSubAreasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getSubAreasResponseBody Body;
        
        public getSubAreasResponse() {
        }
        
        public getSubAreasResponse(YouInteractV1.DSDWS.getSubAreasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSubAreasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.SubArea[] getSubAreasResult;
        
        public getSubAreasResponseBody() {
        }
        
        public getSubAreasResponseBody(You_TimeTables.DSDWS.SubArea[] getSubAreasResult) {
            this.getSubAreasResult = getSubAreasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocentesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocentes", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDocentesRequestBody Body;
        
        public getDocentesRequest() {
        }
        
        public getDocentesRequest(YouInteractV1.DSDWS.getDocentesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDocentesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Rev;
        
        public getDocentesRequestBody() {
        }
        
        public getDocentesRequestBody(int IDDepartamento, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocentesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocentesResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDocentesResponseBody Body;
        
        public getDocentesResponse() {
        }
        
        public getDocentesResponse(YouInteractV1.DSDWS.getDocentesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDocentesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.Docente[] getDocentesResult;
        
        public getDocentesResponseBody() {
        }
        
        public getDocentesResponseBody(You_TimeTables.DSDWS.Docente[] getDocentesResult) {
            this.getDocentesResult = getDocentesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocentesAnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocentesAno", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDocentesAnoRequestBody Body;
        
        public getDocentesAnoRequest() {
        }
        
        public getDocentesAnoRequest(YouInteractV1.DSDWS.getDocentesAnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDocentesAnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getDocentesAnoRequestBody() {
        }
        
        public getDocentesAnoRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocentesAnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocentesAnoResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDocentesAnoResponseBody Body;
        
        public getDocentesAnoResponse() {
        }
        
        public getDocentesAnoResponse(YouInteractV1.DSDWS.getDocentesAnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDocentesAnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.DocenteAno[] getDocentesAnoResult;
        
        public getDocentesAnoResponseBody() {
        }
        
        public getDocentesAnoResponseBody(You_TimeTables.DSDWS.DocenteAno[] getDocentesAnoResult) {
            this.getDocentesAnoResult = getDocentesAnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDisciplinasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDisciplinas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDisciplinasRequestBody Body;
        
        public getDisciplinasRequest() {
        }
        
        public getDisciplinasRequest(YouInteractV1.DSDWS.getDisciplinasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDisciplinasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Rev;
        
        public getDisciplinasRequestBody() {
        }
        
        public getDisciplinasRequestBody(int IDDepartamento, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDisciplinasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDisciplinasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDisciplinasResponseBody Body;
        
        public getDisciplinasResponse() {
        }
        
        public getDisciplinasResponse(YouInteractV1.DSDWS.getDisciplinasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDisciplinasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.Disciplina[] getDisciplinasResult;
        
        public getDisciplinasResponseBody() {
        }
        
        public getDisciplinasResponseBody(You_TimeTables.DSDWS.Disciplina[] getDisciplinasResult) {
            this.getDisciplinasResult = getDisciplinasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDisciplinasAnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDisciplinasAno", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDisciplinasAnoRequestBody Body;
        
        public getDisciplinasAnoRequest() {
        }
        
        public getDisciplinasAnoRequest(YouInteractV1.DSDWS.getDisciplinasAnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDisciplinasAnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getDisciplinasAnoRequestBody() {
        }
        
        public getDisciplinasAnoRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDisciplinasAnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDisciplinasAnoResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getDisciplinasAnoResponseBody Body;
        
        public getDisciplinasAnoResponse() {
        }
        
        public getDisciplinasAnoResponse(YouInteractV1.DSDWS.getDisciplinasAnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDisciplinasAnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.DisciplinaAno[] getDisciplinasAnoResult;
        
        public getDisciplinasAnoResponseBody() {
        }
        
        public getDisciplinasAnoResponseBody(You_TimeTables.DSDWS.DisciplinaAno[] getDisciplinasAnoResult) {
            this.getDisciplinasAnoResult = getDisciplinasAnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTurmasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTurmas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getTurmasRequestBody Body;
        
        public getTurmasRequest() {
        }
        
        public getTurmasRequest(YouInteractV1.DSDWS.getTurmasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTurmasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getTurmasRequestBody() {
        }
        
        public getTurmasRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTurmasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTurmasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getTurmasResponseBody Body;
        
        public getTurmasResponse() {
        }
        
        public getTurmasResponse(YouInteractV1.DSDWS.getTurmasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTurmasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.Turma[] getTurmasResult;
        
        public getTurmasResponseBody() {
        }
        
        public getTurmasResponseBody(You_TimeTables.DSDWS.Turma[] getTurmasResult) {
            this.getTurmasResult = getTurmasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAulasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAulas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getAulasRequestBody Body;
        
        public getAulasRequest() {
        }
        
        public getAulasRequest(YouInteractV1.DSDWS.getAulasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getAulasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getAulasRequestBody() {
        }
        
        public getAulasRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAulasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAulasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getAulasResponseBody Body;
        
        public getAulasResponse() {
        }
        
        public getAulasResponse(YouInteractV1.DSDWS.getAulasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getAulasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.Aula[] getAulasResult;
        
        public getAulasResponseBody() {
        }
        
        public getAulasResponseBody(You_TimeTables.DSDWS.Aula[] getAulasResult) {
            this.getAulasResult = getAulasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTurmasHoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTurmasHora", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getTurmasHoraRequestBody Body;
        
        public getTurmasHoraRequest() {
        }
        
        public getTurmasHoraRequest(YouInteractV1.DSDWS.getTurmasHoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTurmasHoraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getTurmasHoraRequestBody() {
        }
        
        public getTurmasHoraRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTurmasHoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTurmasHoraResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getTurmasHoraResponseBody Body;
        
        public getTurmasHoraResponse() {
        }
        
        public getTurmasHoraResponse(YouInteractV1.DSDWS.getTurmasHoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTurmasHoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.TurmaHora[] getTurmasHoraResult;
        
        public getTurmasHoraResponseBody() {
        }
        
        public getTurmasHoraResponseBody(You_TimeTables.DSDWS.TurmaHora[] getTurmasHoraResult) {
            this.getTurmasHoraResult = getTurmasHoraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWishListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWishList", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getWishListRequestBody Body;
        
        public getWishListRequest() {
        }
        
        public getWishListRequest(YouInteractV1.DSDWS.getWishListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getWishListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getWishListRequestBody() {
        }
        
        public getWishListRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWishListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWishListResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public YouInteractV1.DSDWS.getWishListResponseBody Body;
        
        public getWishListResponse() {
        }
        
        public getWishListResponse(YouInteractV1.DSDWS.getWishListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getWishListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public You_TimeTables.DSDWS.WishList[] getWishListResult;
        
        public getWishListResponseBody() {
        }
        
        public getWishListResponseBody(You_TimeTables.DSDWS.WishList[] getWishListResult) {
            this.getWishListResult = getWishListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : YouInteractV1.DSDWS.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<YouInteractV1.DSDWS.WSSoap>, YouInteractV1.DSDWS.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getSemestresResponse YouInteractV1.DSDWS.WSSoap.getSemestres(YouInteractV1.DSDWS.getSemestresRequest request) {
            return base.Channel.getSemestres(request);
        }
        
        public You_TimeTables.DSDWS.Semestre[] getSemestres(int Rev) {
            YouInteractV1.DSDWS.getSemestresRequest inValue = new YouInteractV1.DSDWS.getSemestresRequest();
            inValue.Body = new YouInteractV1.DSDWS.getSemestresRequestBody();
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getSemestresResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getSemestres(inValue);
            return retVal.Body.getSemestresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getSemestresResponse> YouInteractV1.DSDWS.WSSoap.getSemestresAsync(YouInteractV1.DSDWS.getSemestresRequest request) {
            return base.Channel.getSemestresAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getSemestresResponse> getSemestresAsync(int Rev) {
            YouInteractV1.DSDWS.getSemestresRequest inValue = new YouInteractV1.DSDWS.getSemestresRequest();
            inValue.Body = new YouInteractV1.DSDWS.getSemestresRequestBody();
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getSemestresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getTiposSalaResponse YouInteractV1.DSDWS.WSSoap.getTiposSala(YouInteractV1.DSDWS.getTiposSalaRequest request) {
            return base.Channel.getTiposSala(request);
        }
        
        public You_TimeTables.DSDWS.TipoSala[] getTiposSala(int Rev) {
            YouInteractV1.DSDWS.getTiposSalaRequest inValue = new YouInteractV1.DSDWS.getTiposSalaRequest();
            inValue.Body = new YouInteractV1.DSDWS.getTiposSalaRequestBody();
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getTiposSalaResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getTiposSala(inValue);
            return retVal.Body.getTiposSalaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getTiposSalaResponse> YouInteractV1.DSDWS.WSSoap.getTiposSalaAsync(YouInteractV1.DSDWS.getTiposSalaRequest request) {
            return base.Channel.getTiposSalaAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getTiposSalaResponse> getTiposSalaAsync(int Rev) {
            YouInteractV1.DSDWS.getTiposSalaRequest inValue = new YouInteractV1.DSDWS.getTiposSalaRequest();
            inValue.Body = new YouInteractV1.DSDWS.getTiposSalaRequestBody();
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getTiposSalaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getSalasResponse YouInteractV1.DSDWS.WSSoap.getSalas(YouInteractV1.DSDWS.getSalasRequest request) {
            return base.Channel.getSalas(request);
        }
        
        public You_TimeTables.DSDWS.Sala[] getSalas(int IDDepartamento, int Rev) {
            YouInteractV1.DSDWS.getSalasRequest inValue = new YouInteractV1.DSDWS.getSalasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getSalasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getSalasResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getSalas(inValue);
            return retVal.Body.getSalasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getSalasResponse> YouInteractV1.DSDWS.WSSoap.getSalasAsync(YouInteractV1.DSDWS.getSalasRequest request) {
            return base.Channel.getSalasAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getSalasResponse> getSalasAsync(int IDDepartamento, int Rev) {
            YouInteractV1.DSDWS.getSalasRequest inValue = new YouInteractV1.DSDWS.getSalasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getSalasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getSalasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getCursosResponse YouInteractV1.DSDWS.WSSoap.getCursos(YouInteractV1.DSDWS.getCursosRequest request) {
            return base.Channel.getCursos(request);
        }
        
        public You_TimeTables.DSDWS.Curso[] getCursos(int IDDepartamento, int Rev) {
            YouInteractV1.DSDWS.getCursosRequest inValue = new YouInteractV1.DSDWS.getCursosRequest();
            inValue.Body = new YouInteractV1.DSDWS.getCursosRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getCursosResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getCursos(inValue);
            return retVal.Body.getCursosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getCursosResponse> YouInteractV1.DSDWS.WSSoap.getCursosAsync(YouInteractV1.DSDWS.getCursosRequest request) {
            return base.Channel.getCursosAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getCursosResponse> getCursosAsync(int IDDepartamento, int Rev) {
            YouInteractV1.DSDWS.getCursosRequest inValue = new YouInteractV1.DSDWS.getCursosRequest();
            inValue.Body = new YouInteractV1.DSDWS.getCursosRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getCursosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getDepartamentosResponse YouInteractV1.DSDWS.WSSoap.getDepartamentos(YouInteractV1.DSDWS.getDepartamentosRequest request) {
            return base.Channel.getDepartamentos(request);
        }
        
        public You_TimeTables.DSDWS.Departamento[] getDepartamentos(int Rev) {
            YouInteractV1.DSDWS.getDepartamentosRequest inValue = new YouInteractV1.DSDWS.getDepartamentosRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDepartamentosRequestBody();
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getDepartamentosResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getDepartamentos(inValue);
            return retVal.Body.getDepartamentosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDepartamentosResponse> YouInteractV1.DSDWS.WSSoap.getDepartamentosAsync(YouInteractV1.DSDWS.getDepartamentosRequest request) {
            return base.Channel.getDepartamentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDepartamentosResponse> getDepartamentosAsync(int Rev) {
            YouInteractV1.DSDWS.getDepartamentosRequest inValue = new YouInteractV1.DSDWS.getDepartamentosRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDepartamentosRequestBody();
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getDepartamentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getAreasResponse YouInteractV1.DSDWS.WSSoap.getAreas(YouInteractV1.DSDWS.getAreasRequest request) {
            return base.Channel.getAreas(request);
        }
        
        public You_TimeTables.DSDWS.Area[] getAreas(int Rev) {
            YouInteractV1.DSDWS.getAreasRequest inValue = new YouInteractV1.DSDWS.getAreasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getAreasRequestBody();
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getAreasResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getAreas(inValue);
            return retVal.Body.getAreasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getAreasResponse> YouInteractV1.DSDWS.WSSoap.getAreasAsync(YouInteractV1.DSDWS.getAreasRequest request) {
            return base.Channel.getAreasAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getAreasResponse> getAreasAsync(int Rev) {
            YouInteractV1.DSDWS.getAreasRequest inValue = new YouInteractV1.DSDWS.getAreasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getAreasRequestBody();
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getAreasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getSubAreasResponse YouInteractV1.DSDWS.WSSoap.getSubAreas(YouInteractV1.DSDWS.getSubAreasRequest request) {
            return base.Channel.getSubAreas(request);
        }
        
        public You_TimeTables.DSDWS.SubArea[] getSubAreas(int Rev) {
            YouInteractV1.DSDWS.getSubAreasRequest inValue = new YouInteractV1.DSDWS.getSubAreasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getSubAreasRequestBody();
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getSubAreasResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getSubAreas(inValue);
            return retVal.Body.getSubAreasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getSubAreasResponse> YouInteractV1.DSDWS.WSSoap.getSubAreasAsync(YouInteractV1.DSDWS.getSubAreasRequest request) {
            return base.Channel.getSubAreasAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getSubAreasResponse> getSubAreasAsync(int Rev) {
            YouInteractV1.DSDWS.getSubAreasRequest inValue = new YouInteractV1.DSDWS.getSubAreasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getSubAreasRequestBody();
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getSubAreasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getDocentesResponse YouInteractV1.DSDWS.WSSoap.getDocentes(YouInteractV1.DSDWS.getDocentesRequest request) {
            return base.Channel.getDocentes(request);
        }
        
        public You_TimeTables.DSDWS.Docente[] getDocentes(int IDDepartamento, int Rev) {
            YouInteractV1.DSDWS.getDocentesRequest inValue = new YouInteractV1.DSDWS.getDocentesRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDocentesRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getDocentesResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getDocentes(inValue);
            return retVal.Body.getDocentesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDocentesResponse> YouInteractV1.DSDWS.WSSoap.getDocentesAsync(YouInteractV1.DSDWS.getDocentesRequest request) {
            return base.Channel.getDocentesAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDocentesResponse> getDocentesAsync(int IDDepartamento, int Rev) {
            YouInteractV1.DSDWS.getDocentesRequest inValue = new YouInteractV1.DSDWS.getDocentesRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDocentesRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getDocentesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getDocentesAnoResponse YouInteractV1.DSDWS.WSSoap.getDocentesAno(YouInteractV1.DSDWS.getDocentesAnoRequest request) {
            return base.Channel.getDocentesAno(request);
        }
        
        public You_TimeTables.DSDWS.DocenteAno[] getDocentesAno(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getDocentesAnoRequest inValue = new YouInteractV1.DSDWS.getDocentesAnoRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDocentesAnoRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getDocentesAnoResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getDocentesAno(inValue);
            return retVal.Body.getDocentesAnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDocentesAnoResponse> YouInteractV1.DSDWS.WSSoap.getDocentesAnoAsync(YouInteractV1.DSDWS.getDocentesAnoRequest request) {
            return base.Channel.getDocentesAnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDocentesAnoResponse> getDocentesAnoAsync(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getDocentesAnoRequest inValue = new YouInteractV1.DSDWS.getDocentesAnoRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDocentesAnoRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getDocentesAnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getDisciplinasResponse YouInteractV1.DSDWS.WSSoap.getDisciplinas(YouInteractV1.DSDWS.getDisciplinasRequest request) {
            return base.Channel.getDisciplinas(request);
        }
        
        public You_TimeTables.DSDWS.Disciplina[] getDisciplinas(int IDDepartamento, int Rev) {
            YouInteractV1.DSDWS.getDisciplinasRequest inValue = new YouInteractV1.DSDWS.getDisciplinasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDisciplinasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getDisciplinasResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getDisciplinas(inValue);
            return retVal.Body.getDisciplinasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDisciplinasResponse> YouInteractV1.DSDWS.WSSoap.getDisciplinasAsync(YouInteractV1.DSDWS.getDisciplinasRequest request) {
            return base.Channel.getDisciplinasAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDisciplinasResponse> getDisciplinasAsync(int IDDepartamento, int Rev) {
            YouInteractV1.DSDWS.getDisciplinasRequest inValue = new YouInteractV1.DSDWS.getDisciplinasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDisciplinasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getDisciplinasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getDisciplinasAnoResponse YouInteractV1.DSDWS.WSSoap.getDisciplinasAno(YouInteractV1.DSDWS.getDisciplinasAnoRequest request) {
            return base.Channel.getDisciplinasAno(request);
        }
        
        public You_TimeTables.DSDWS.DisciplinaAno[] getDisciplinasAno(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getDisciplinasAnoRequest inValue = new YouInteractV1.DSDWS.getDisciplinasAnoRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDisciplinasAnoRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getDisciplinasAnoResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getDisciplinasAno(inValue);
            return retVal.Body.getDisciplinasAnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDisciplinasAnoResponse> YouInteractV1.DSDWS.WSSoap.getDisciplinasAnoAsync(YouInteractV1.DSDWS.getDisciplinasAnoRequest request) {
            return base.Channel.getDisciplinasAnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getDisciplinasAnoResponse> getDisciplinasAnoAsync(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getDisciplinasAnoRequest inValue = new YouInteractV1.DSDWS.getDisciplinasAnoRequest();
            inValue.Body = new YouInteractV1.DSDWS.getDisciplinasAnoRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getDisciplinasAnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getTurmasResponse YouInteractV1.DSDWS.WSSoap.getTurmas(YouInteractV1.DSDWS.getTurmasRequest request) {
            return base.Channel.getTurmas(request);
        }
        
        public You_TimeTables.DSDWS.Turma[] getTurmas(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getTurmasRequest inValue = new YouInteractV1.DSDWS.getTurmasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getTurmasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getTurmasResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getTurmas(inValue);
            return retVal.Body.getTurmasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getTurmasResponse> YouInteractV1.DSDWS.WSSoap.getTurmasAsync(YouInteractV1.DSDWS.getTurmasRequest request) {
            return base.Channel.getTurmasAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getTurmasResponse> getTurmasAsync(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getTurmasRequest inValue = new YouInteractV1.DSDWS.getTurmasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getTurmasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getTurmasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getAulasResponse YouInteractV1.DSDWS.WSSoap.getAulas(YouInteractV1.DSDWS.getAulasRequest request) {
            return base.Channel.getAulas(request);
        }
        
        public You_TimeTables.DSDWS.Aula[] getAulas(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getAulasRequest inValue = new YouInteractV1.DSDWS.getAulasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getAulasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getAulasResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getAulas(inValue);
            return retVal.Body.getAulasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getAulasResponse> YouInteractV1.DSDWS.WSSoap.getAulasAsync(YouInteractV1.DSDWS.getAulasRequest request) {
            return base.Channel.getAulasAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getAulasResponse> getAulasAsync(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getAulasRequest inValue = new YouInteractV1.DSDWS.getAulasRequest();
            inValue.Body = new YouInteractV1.DSDWS.getAulasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getAulasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getTurmasHoraResponse YouInteractV1.DSDWS.WSSoap.getTurmasHora(YouInteractV1.DSDWS.getTurmasHoraRequest request) {
            return base.Channel.getTurmasHora(request);
        }
        
        public You_TimeTables.DSDWS.TurmaHora[] getTurmasHora(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getTurmasHoraRequest inValue = new YouInteractV1.DSDWS.getTurmasHoraRequest();
            inValue.Body = new YouInteractV1.DSDWS.getTurmasHoraRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getTurmasHoraResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getTurmasHora(inValue);
            return retVal.Body.getTurmasHoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getTurmasHoraResponse> YouInteractV1.DSDWS.WSSoap.getTurmasHoraAsync(YouInteractV1.DSDWS.getTurmasHoraRequest request) {
            return base.Channel.getTurmasHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getTurmasHoraResponse> getTurmasHoraAsync(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getTurmasHoraRequest inValue = new YouInteractV1.DSDWS.getTurmasHoraRequest();
            inValue.Body = new YouInteractV1.DSDWS.getTurmasHoraRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getTurmasHoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YouInteractV1.DSDWS.getWishListResponse YouInteractV1.DSDWS.WSSoap.getWishList(YouInteractV1.DSDWS.getWishListRequest request) {
            return base.Channel.getWishList(request);
        }
        
        public You_TimeTables.DSDWS.WishList[] getWishList(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getWishListRequest inValue = new YouInteractV1.DSDWS.getWishListRequest();
            inValue.Body = new YouInteractV1.DSDWS.getWishListRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            YouInteractV1.DSDWS.getWishListResponse retVal = ((YouInteractV1.DSDWS.WSSoap)(this)).getWishList(inValue);
            return retVal.Body.getWishListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YouInteractV1.DSDWS.getWishListResponse> YouInteractV1.DSDWS.WSSoap.getWishListAsync(YouInteractV1.DSDWS.getWishListRequest request) {
            return base.Channel.getWishListAsync(request);
        }
        
        public System.Threading.Tasks.Task<YouInteractV1.DSDWS.getWishListResponse> getWishListAsync(int IDDepartamento, int IDSemestre, int Rev) {
            YouInteractV1.DSDWS.getWishListRequest inValue = new YouInteractV1.DSDWS.getWishListRequest();
            inValue.Body = new YouInteractV1.DSDWS.getWishListRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            return ((YouInteractV1.DSDWS.WSSoap)(this)).getWishListAsync(inValue);
        }
    }
}
