//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generic_configs
    {
        public generic_configs()
        {
            this.generic_config_items = new HashSet<generic_config_items>();
            this.generic_devices = new HashSet<generic_devices>();
        }
    
        public int id { get; set; }
        public int template_id { get; set; }
        public int scheduler_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public byte @default { get; set; }
        public byte status { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual ICollection<generic_config_items> generic_config_items { get; set; }
        public virtual generic_schedulers generic_schedulers { get; set; }
        public virtual generic_templates generic_templates { get; set; }
        public virtual ICollection<generic_devices> generic_devices { get; set; }
    }
}
