//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generic_scheduler_items
    {
        public int id { get; set; }
        public int scheduler_id { get; set; }
        public int config_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual generic_scheduler_configs generic_scheduler_configs { get; set; }
        public virtual generic_schedulers generic_schedulers { get; set; }
    }
}
