//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generic_items
    {
        public generic_items()
        {
            this.generic_config_items = new HashSet<generic_config_items>();
            this.generic_scheduler_config_items = new HashSet<generic_scheduler_config_items>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string file { get; set; }
        public byte type { get; set; }
        public string code { get; set; }
        public string preview { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual ICollection<generic_config_items> generic_config_items { get; set; }
        public virtual ICollection<generic_scheduler_config_items> generic_scheduler_config_items { get; set; }
    }
}
