//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generic_schedulers
    {
        public generic_schedulers()
        {
            this.generic_configs = new HashSet<generic_configs>();
            this.generic_scheduler_items = new HashSet<generic_scheduler_items>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public byte status { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual ICollection<generic_configs> generic_configs { get; set; }
        public virtual ICollection<generic_scheduler_items> generic_scheduler_items { get; set; }
    }
}
