//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kinect_items
    {
        public kinect_items()
        {
            this.kinect_config_items = new HashSet<kinect_config_items>();
            this.kinect_items_download = new HashSet<kinect_items_download>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string dll { get; set; }
        public string version { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual ICollection<kinect_config_items> kinect_config_items { get; set; }
        public virtual ICollection<kinect_items_download> kinect_items_download { get; set; }
    }
}
