//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kinect_scheduler_config_items
    {
        public kinect_scheduler_config_items()
        {
            this.kinect_scheduler_configs = new HashSet<kinect_scheduler_configs>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string file { get; set; }
        public string preview { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual ICollection<kinect_scheduler_configs> kinect_scheduler_configs { get; set; }
    }
}
