//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kinect_config_items
    {
        public int id { get; set; }
        public int config_id { get; set; }
        public int item_id { get; set; }
        public byte status { get; set; }
        public int priority { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual kinect_configs kinect_configs { get; set; }
        public virtual kinect_items kinect_items { get; set; }
    }
}
