//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kinect_configs
    {
        public kinect_configs()
        {
            this.kinect_config_items = new HashSet<kinect_config_items>();
            this.kinect_devices = new HashSet<kinect_devices>();
        }
    
        public int id { get; set; }
        public int template_id { get; set; }
        public int scheduler_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public byte @default { get; set; }
        public byte status { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual ICollection<kinect_config_items> kinect_config_items { get; set; }
        public virtual kinect_schedulers kinect_schedulers { get; set; }
        public virtual kinect_templates kinect_templates { get; set; }
        public virtual ICollection<kinect_devices> kinect_devices { get; set; }
    }
}
