//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities2 : DbContext
    {
        public DatabaseEntities2()
            : base("name=DatabaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<generic_config_items> generic_config_items { get; set; }
        public virtual DbSet<generic_configs> generic_configs { get; set; }
        public virtual DbSet<generic_devices> generic_devices { get; set; }
        public virtual DbSet<generic_items> generic_items { get; set; }
        public virtual DbSet<generic_scheduler_config_items> generic_scheduler_config_items { get; set; }
        public virtual DbSet<generic_scheduler_configs> generic_scheduler_configs { get; set; }
        public virtual DbSet<generic_scheduler_items> generic_scheduler_items { get; set; }
        public virtual DbSet<generic_schedulers> generic_schedulers { get; set; }
        public virtual DbSet<generic_templates> generic_templates { get; set; }
        public virtual DbSet<kinect_config_items> kinect_config_items { get; set; }
        public virtual DbSet<kinect_configs> kinect_configs { get; set; }
        public virtual DbSet<kinect_devices> kinect_devices { get; set; }
        public virtual DbSet<kinect_items> kinect_items { get; set; }
        public virtual DbSet<kinect_items_download> kinect_items_download { get; set; }
        public virtual DbSet<kinect_scheduler_config_items> kinect_scheduler_config_items { get; set; }
        public virtual DbSet<kinect_scheduler_configs> kinect_scheduler_configs { get; set; }
        public virtual DbSet<kinect_scheduler_items> kinect_scheduler_items { get; set; }
        public virtual DbSet<kinect_schedulers> kinect_schedulers { get; set; }
        public virtual DbSet<kinect_templates> kinect_templates { get; set; }
    }
}
