//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portalYI.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public class user
    {
        public int id { get; set; }

        public string name { get; set; }

        [Required(ErrorMessage="Please provide email", AllowEmptyStrings=false)]
        public string email { get; set; }


        [Required(ErrorMessage = "Please provide email", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string password { get; set; }

        [Display(Name = "Remember me?")]
        public string remember_token { get; set; }

        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
